# -*- coding: utf-8 -*-
"""day_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fxf-AE1DPb96sQGu7mLli_CG0Jze6-J7
"""



"""If else elif statement"""

print("Welcome of rollaercoaster ride")
height=int(input("enter your height"))
if height>120:
  age=int(input("enter the age"))
  if age<=12:
    print("ride price is $5")
  elif 18>age>12:
    print('ride price is $7')
  else:
    print('ride price is $12')



else:
  print("you can't ride")

print("The Love Calculator is calculating your score...")
name1 = input() # What is your name?
name2 = input() # What is their name?
# 🚨 Don't change the code above 👆
# Write your code below this line 👇
name1=name1.upper()
name2=name2.upper()
total=name1+name2
t=total.count('T')
r=total.count('R')
u=total.count('U')
e=total.count('E')
count=str(t+r+u+e)
l=total.count('L')
o=total.count('O')
v=total.count('V')
e_=total.count('E')
count2=str(l+o+v+e_)
total2=count+count2
print(f"Your score is {total2}.")

"""Treasure island project"""

print('Welcome to Treasure Island.Your mission is to find the treasure')
option=input('You are at a cross road. Where do yu want to go? Type "left" or "right":\n')
if option=='left':
  option1=input("swin or wait")
  if option1=='wait':
    option2=input('Which door? "Red" , "Yellow", "Blue", or "Anything else"?\n')
    if option2=='yellow':
      print('you win')
    elif option2=='blue':
      print('Eaten by beasts.Game Over')
    elif option2=='red':
      print('Burned by fire.Game Over')
    else:
      print('game over')
  else:
    print("Attacked by trout.Game Over")
else :
  print('Fall into a hole.Game Over')