# -*- coding: utf-8 -*-
"""day_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EoJ7MM80rNKKNNrll311qfsnlkHfnsTn
"""

https://app.auditorium.ai/courses/eelyNMYJKXeNJAbjssSEQz0m88XvnhX6
#audotorium platform

print("hello world\nhello world")

print("hello" +' '+ "world")

"""Band name genrater program"""

print("Welcome to the Band Name Generator.")
street = input("What's the name of the city you grew up in?\n")
pet = input("What's your pet's name?\n")
print("Your band name could be " + street + " " + pet)