# -*- coding: utf-8 -*-
"""day_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BPydGThhTHS6xl9Q64q1_5igaVIzZstY
"""

import numpy as np
import matplotlib.pyplot as plt
x=np.linspace(-1,1,100)
print(x)
def ReLU(x):
  return np.maximum(0,x)

y=ReLU(x)
plt.plot(x,y)
round(7/3,2)

import math
test_h = int(input()) # Height of wall (m)
test_w = int(input()) # Width of wall (m)
coverage = 5

def paint_calc(height,width,cover):
  num=math.ceil((height*width)/cover)

  print(f"You'll need {num} cans of paint.")
paint_calc(height=test_h, width=test_w, cover=coverage)

math.floor(7/3)

"""Caesar cipher"""

alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
            'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',]

direction = input("Type 'encode' to encrypt, type 'decode' to decrypt:\n")
text = input("Type your message:\n").lower()
shift = int(input("Type the shift number:\n"))
def encrypt(text,shift):
  l=[]
  for i in range(0,len(text)):
    char=text[i]
    num1=alphabet.index(char)
    num2=num1+shift
    l.append(alphabet[num2])

  string=''.join(l)
  print(string)

def decrypt(text,shift):
  l=[]
  for i in range(0,len(text)):
    char=text[i]
    num1=alphabet.index(char)
    num2=num1-shift
    l.append(alphabet[num2])

  string=''.join(l)
  print(string)
if direction=="encode" :
  encrypt(text,shift)
else:
  decrypt(text,shift)



alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
            'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',]
logo = """
 ,adPPYba, ,adPPYYba,  ,adPPYba, ,adPPYba, ,adPPYYba, 8b,dPPYba,
a8"     "" ""     `Y8 a8P_____88 I8[    "" ""     `Y8 88P'   "Y8
8b         ,adPPPPP88 8PP"""""""  `"Y8ba,  ,adPPPPP88 88
"8a,   ,aa 88,    ,88 "8b,   ,aa aa    ]8I 88,    ,88 88
 `"Ybbd8"' `"8bbdP"Y8  `"Ybbd8"' `"YbbdP"' `"8bbdP"Y8 88
            88             88
           ""             88
                          88
 ,adPPYba, 88 8b,dPPYba,  88,dPPYba,   ,adPPYba, 8b,dPPYba,
a8"     "" 88 88P'    "8a 88P'    "8a a8P_____88 88P'   "Y8
8b         88 88       d8 88       88 8PP""""""" 88
"8a,   ,aa 88 88b,   ,a8" 88       88 "8b,   ,aa 88
 `"Ybbd8"' 88 88`YbbdP"'  88       88  `"Ybbd8"' 88
              88
              88
"""
print(logo)
should_end = False
while not should_end:

  direction = input("Type 'encode' to encrypt, type 'decode' to decrypt:\n")
  text = input("Type your message:\n").lower()
  shift = int(input("Type the shift number:\n"))

  shift = shift % 26

  caesar(text,shift,direction)

  restart = input("Type 'yes' if you want to go again. Otherwise type 'no'.\n")
  if restart == "no":
    should_end = True
    print("Goodbye")

def caesar(text,shift,direction):
  l=[]
  for i in range(0,len(text)):
    char=text[i]
    if char in alphabet:
      num1=alphabet.index(char)
      if direction=='encode':
        shift=shift
        num2=num1+shift
      else:
        num2=num1-shift
      l.append(alphabet[num2])
    else:
      l.append(char)

  string=''.join(l)
  print(f'the {direction} messeage is {string}')

