# -*- coding: utf-8 -*-
"""day_9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OMRh2y-D7nwPvfES4cCh-iW8rW95935K

Secret auction program
"""



logo = '''
                         ___________
                         \         /
                          )_______(
                          |"""""""|_.-._,.---------.,_.-._
                          |       | | |               | | ''-.
                          |       |_| |_             _| |_..-'
                          |_______| '-' `'---------'` '-'
                          )"""""""(
                         /_________\\
                       .-------------.
                      /_______________\\
'''
print(logo)
process=False
record={}
while not process:
  name=input('What is you name?')
  bid_amount=int(input("What's you bid?"))
  record[name]=bid_amount
  bidder=input("are ther any other bidders? Type 'Yes' or 'not' ")
  if bidder=='not':
    max=0
    name=''
    process=True
    for i in record:
      if record[i]>max:
        max=record[i]
        name=i
    print(f'max amount of bid is {max} by {name}')

