# -*- coding: utf-8 -*-
"""day_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J10LPeB10UWRwmE159anBD3kvcYN1ueT
"""

def my_function(a):
    if a < 40:
        return
        print("Terrible")
    if a < 80:
        return "Pass"
    else:
        return "Great"
print(my_function(25))

def calculater(a,b,operation):
  if operation=='+':
    return a+b
  elif operation=='-':
    return a-b
  elif operation=='*':
    return a*b
  elif operation=='/':
    return a/b
  else:
    return 'invalid operation'

bools=False
while not bools:
  a=float(input("What's is the first number? "))
  print('+\n-\n*\n/')
  operation=input("Pick an operation:")
  b=float(input("What's is the second number? "))
  value=calculater(a,b,operation)
  print(f"{a}{operation}{b}={value}")
  user=input("You want to continoue the program Type 'yes' or 'not'")
  if user=='not':
    bools=True

