# -*- coding: utf-8 -*-
"""day_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-YErmkhWKDM7YHDciodkDDbBdGYpr9HO
"""

import random
integer=random.randint(1,6)
f=random.random()
total=f+integer
total

import random
a=int(input('1 or 0'))
if a==1:
  print('Heads')
else:
  print("Tails")

import random
names_string=input()
names = names_string.split(", ")
length=len(names)
b=random.randint(0,length-1)
print(f'{names[b]} is going to buy the meal today!')

"""Rock paper scissors"""

rock = '''
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
'''

paper = '''
    _______
---'   ____)____
          ______)
          _______)
         _______)
---.__________)
'''

scissors = '''
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
'''
option=[rock,paper,scissors]

user_input=int(input("What you want to choose type 0 for rock or type 1 for paper or type 2 for scissors "))
print(option[user_input])
computer_input=random.randint(0,2)

print(option[computer_input])
if user_input==0:
  if computer_input==1:
    print("computer win")
  elif computer_input==2:
    print("you win")
  else:
    print("draw")
elif user_input==1:
  if computer_input==2:
    print("computer win")
  elif computer_input==0:
    print("you win ")
  else:
    print("draw")


elif user_input==2:
  if computer_input==0:
    print('computer win' )
  if computer_input==1:
    print('you win')
  else :
    print("draw")