# -*- coding: utf-8 -*-
"""day_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QmULoVnDYwdAAPu-A7vRVaa4LqSPQI_P

Function and While loop
"""

def turn_right():
  turn_left()
  turn_left()
  turn_left()
while not at_goal():

  if right_is_clear():
    turn_right()
    move()
  elif front_is_clear():
    move()
  else:
    turn_left()

