# -*- coding: utf-8 -*-
"""day_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JtaEkRPBk-SOnDQ1bX6tVMUMXLBJR2US

Data Types Type converstion Operation F string

Data type

1 string

2 integer

3 float

4 boolen

Mathematic operation +,-,/,*
"""

2**3

round(8/3,4)

num=56
num2=7.89
print(f"hello {num} and {num2}")

"""Tip Calculater program

"""

print("Welocome to tip calculator!")
num1=float(input("What was the total bill $"))
num2=int(input("How much tip would you like to give ? 10 ,12,or 15"))
person=int(input("How many people to split the bill "))
num2=(num1*num2)/100
total_bill=num1+num2
each=round(total_bill/person,2)

print(f"Each person should pay: ${each}")