# -*- coding: utf-8 -*-
"""days_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/138hUgGzWPifoVLBTN7tjakTyyIVRV8CY

Loops
"""

# Input a list of student scores
student_scores = input().split()
for n in range(0, len(student_scores)):
  student_scores[n] = int(student_scores[n])
min=student_scores[1]
# Write your code below this row 👇
for i in range(0,len(student_scores)):
  if min<student_scores[i]:
    min=student_scores[i]

print(min)

"""Pypassword genrater program"""

import random
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols = ['!', '#', '$', '%', '&', '(', ')', '*', '+']

print("Welcome to the PyPassword Generator!")
nr_letters= int(input("How many letters would you like in your password?\n"))
nr_symbols = int(input(f"How many symbols would you like?\n"))
nr_numbers = int(input(f"How many numbers would you like?\n"))

letter=''
for i in range(0,nr_letters):
  letter+=random.choice(letters)
number=''
for i in range(0,nr_numbers):
  number+=random.choice(numbers)
symbol=''
for i in range(0,nr_symbols):
  symbol+=random.choice(symbols)
password=letter+number+symbol
char_list = list(password)
random.shuffle(char_list)
shuffled_string = ''.join(char_list)


print(f"Here is your passwprd {shuffled_string}")
