# -*- coding: utf-8 -*-
"""day_12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jk_iMRSMvhph8lfZj1WJUPs-dIv9wAYF

LOCAL AND GLOBLE SCOPE IN PYTHON IS VALID FOR FUNCTION ONLY NOT VALID FOR LOOPS AND IF AND ELSE
"""

day=1
def increase():
  global day
  day+=13#NOT A VALID CODE WE CAN CHANGE GLOBAL VARIABLE
  print("hello")

increase()

day=3
def increase():
  return day+1

print(increase())

"""Number guessing game"""

import random
bools=False
while not bools:
  number=random.randrange(1,101)
  print("welcome to number gusssing game!")
  print("I am thinking of a number between 1 to 100")
  level=input("Choose a difficulty level type 'esay' or 'hard':")
  def condition(attempt):
    while attempt!=0:
      print(f"You have {attempt} remaining to guess")
      guess=int(input("Make a guess:"))
      if guess>number:
        print("Too high")
        attempt=attempt-1
      elif guess<number:
        print("Too low")
        attempt=attempt-1
      elif guess==number:
        print("You won")
        break
      if attempt==0:
        print("You loss")

  if level=='easy':
    condition(10)
  else:
    condition(5)
  a=input("Do you want to play again or not")
  if a=='not':
    bools=True

import random
print(random.randrange(5,8))